### ISSUE TITLE
Does not compile with crystal 1.3.x

### ISSUE THREAD

**Issue by postmodern** [busyloop/user_agent_parser#1]
Hello, I needed to parse some User-Agent strings quickly with Crystal and tried your shard. It appears the [YAML](https://crystal-lang.org/api/1.3.2/YAML.html) API has changed since you created this shard.

### Example

```crystal
require "user_agent_parser"

ua = UserAgent.new("Mozilla/5.0 (Linux; Android 7.0; SM-G892A Build/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/60.0.3112.107 Mobile Safari/537.36")

p ua.family
```

### Error

```
In src/test.cr:1:1

 1 | require "user_agent_parser"
     ^
Error: while requiring "user_agent_parser"


In lib/user_agent_parser/src/user_agent_parser.cr:28:10

 28 | YAML.mapping(
           ^------
Error: undefined method 'mapping' for YAML:Module

YAML:Module trace:

  lib/user_agent_parser/src/user_agent_parser.cr:28

        YAML.mapping(

```

**Comment by m-o-e** [comment]
Thanks for the heads up, had indeed not used this shard in a long time.
I've made a new release (v2.0.0) that should work with crystal v1.3.2 now,
please let me know if you still run into trouble.

(note: I've also removed the auto-download of the regexes, see README for updated instructions)

**Comment by postmodern** [comment]
Works now, thanks!

**Comment by postmodern** [comment]
As for docs, I just manually `cp -r doc/` and commit them to my GitHub Pages website when doing a release. Others setup GitHub Actions to automatically deploy docs to the repos' own GitHub Pages upon release.

**Comment by m-o-e** [comment]
Yup, they used to be generated with travis, but travis.org was apparently discontinued (it's now .com),
so might move to some other CI at some point.

But I believe the shard is largely self explanatory anyway, so probably not gonna happen very soon. ;)
